/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package piano;

/**
 *
 * @author Thomas
 */

import java.io.*;
import java.awt.Color;

public class PianoGUI extends javax.swing.JFrame {
    boolean shiftDown = false;
    /**
     * Creates new form PianoGUI
     */
    public PianoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        chatBox1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        chatBox2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        pianoArea = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Piano");
        setBackground(new java.awt.Color(51, 51, 51));

        chatBox1.setText("john");
        chatBox1.setToolTipText("");
        chatBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatBox1ActionPerformed(evt);
            }
        });
        chatBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chatBox1KeyPressed(evt);
            }
        });

        chatBox2.setEditable(false);
        chatBox2.setColumns(20);
        chatBox2.setRows(5);
        jScrollPane3.setViewportView(chatBox2);

        pianoArea.setEditable(false);
        pianoArea.setColumns(20);
        pianoArea.setRows(5);
        pianoArea.setText("piano here");
        pianoArea.setToolTipText("");
        pianoArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pianoAreaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pianoAreaKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(pianoArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(chatBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chatBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4))
                .addContainerGap(363, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chatBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chatBox1ActionPerformed

    private void chatBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chatBox1KeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        switch(key){
            case 10:
                try{
                    PianoClient.out.writeUTF("." + chatBox1.getText());
                }catch(IOException e){
                    
                }
                chatBox1.setText("");
                break;
            default:
        }
    }//GEN-LAST:event_chatBox1KeyPressed

    private void pianoAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pianoAreaKeyPressed
        // TODO add your handling code here:
        int keyInt = evt.getKeyCode();
        char keyChar = evt.getKeyChar();
        if (keyInt == 16){
            shiftDown = true;
        }
        if(shiftDown){
            try{
                PianoClient.out.writeUTF(Character.toString(keyChar));
            }catch(IOException e){
                
            }
        }else{
            try{
                PianoClient.out.writeUTF(Character.toString(keyChar).toLowerCase());
            }catch(IOException e){
                
            }
        }
    }//GEN-LAST:event_pianoAreaKeyPressed

    private void pianoAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pianoAreaKeyReleased
        // TODO add your handling code here:
        int keyInt = evt.getKeyCode();
        if (keyInt == 16){
            shiftDown = false;
        }
    }//GEN-LAST:event_pianoAreaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PianoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PianoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PianoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PianoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PianoGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField chatBox1;
    public static javax.swing.JTextArea chatBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private java.awt.Panel panel13;
    private java.awt.Panel panel14;
    private java.awt.Panel panel17;
    private java.awt.Panel panel8;
    private java.awt.Panel panel9;
    private javax.swing.JTextArea pianoArea;
    // End of variables declaration//GEN-END:variables
}

