/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package piano;

/**
 *
 * @author Thomas
 */

import java.io.*;
import java.awt.Color;

public class PianoGUI extends javax.swing.JFrame {
    
    //30 colors for gradient
    
    Color[] Colors = {new Color(0,0,44),new Color(5, 5, 60),new Color(9,9,70),new Color(12,12,80),
                        new Color(15,15,90), new Color(18,18,100), new Color(20,20,110),new Color(26,26,120),
                        new Color(31,31,128), new Color(36,36,138), new Color(45,45,136), new Color(51,51,149),
                        new Color(62,62,161), new Color(72,72,171), new Color(81,81,176), new Color(91,91,185),
                        new Color(99,99,188), new Color(110,100,192), new Color(120,120,198), new Color(131,131,202),
                        new Color (144,144,210), new Color(155,155,212), new Color(168,168,216), new Color(180,180,222),
                        new Color(191,191,225), new Color(201,201,228), new Color(215,215,235), new Color(234,234,240),
                        new Color(240,240,242), new Color(255,255,255)};
    
    int _1, _2, _3, _4, _5, _6, _7, _8, _9, _0, _q, _w, _e, _r, _t, _y, _u, _i, _o, _p, _a, _s, _d, _f, _g, _h, _j, _k, _l,
            _z, _x, _c, _v, _b, _n, _m, __1, __2, __4, __5, __6, __8, __9, _Q, _E, _T, _Y, _I, _O, _P, _S, _D, _G, _H, _J, 
            _L, _Z, _C, _V, _B;
    
    boolean shiftDown = false;
    /**
     * Creates new form PianoGUI
     */
    public PianoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chatBox1 = new javax.swing.JTextField();
        panel1 = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        jScrollPane3 = new javax.swing.JScrollPane();
        chatBox2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        pianoArea = new javax.swing.JTextArea();
        panel62 = new java.awt.Panel();
        panel63 = new java.awt.Panel();
        panel64 = new java.awt.Panel();
        panel65 = new java.awt.Panel();
        panel66 = new java.awt.Panel();
        panel67 = new java.awt.Panel();
        panel68 = new java.awt.Panel();
        panel69 = new java.awt.Panel();
        panel70 = new java.awt.Panel();
        panel71 = new java.awt.Panel();
        panel72 = new java.awt.Panel();
        panel73 = new java.awt.Panel();
        panel74 = new java.awt.Panel();
        panel75 = new java.awt.Panel();
        panel76 = new java.awt.Panel();
        panel77 = new java.awt.Panel();
        panel78 = new java.awt.Panel();
        panel79 = new java.awt.Panel();
        panel80 = new java.awt.Panel();
        panel81 = new java.awt.Panel();
        panel82 = new java.awt.Panel();
        panel83 = new java.awt.Panel();
        panel84 = new java.awt.Panel();
        panel85 = new java.awt.Panel();
        panel86 = new java.awt.Panel();
        panel87 = new java.awt.Panel();
        panel88 = new java.awt.Panel();
        panel89 = new java.awt.Panel();
        panel90 = new java.awt.Panel();
        panel91 = new java.awt.Panel();
        panel92 = new java.awt.Panel();
        panel93 = new java.awt.Panel();
        panel94 = new java.awt.Panel();
        panel95 = new java.awt.Panel();
        panel96 = new java.awt.Panel();
        panel97 = new java.awt.Panel();
        panel98 = new java.awt.Panel();
        panel99 = new java.awt.Panel();
        panel100 = new java.awt.Panel();
        panel101 = new java.awt.Panel();
        panel102 = new java.awt.Panel();
        panel103 = new java.awt.Panel();
        panel104 = new java.awt.Panel();
        panel105 = new java.awt.Panel();
        panel106 = new java.awt.Panel();
        panel107 = new java.awt.Panel();
        panel108 = new java.awt.Panel();
        panel109 = new java.awt.Panel();
        panel110 = new java.awt.Panel();
        panel111 = new java.awt.Panel();
        panel112 = new java.awt.Panel();
        panel113 = new java.awt.Panel();
        panel114 = new java.awt.Panel();
        panel115 = new java.awt.Panel();
        panel116 = new java.awt.Panel();
        panel117 = new java.awt.Panel();
        panel118 = new java.awt.Panel();
        panel119 = new java.awt.Panel();
        panel120 = new java.awt.Panel();
        panel121 = new java.awt.Panel();
        panel122 = new java.awt.Panel();
        panel123 = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chatBox1.setText("first thing you type here is your username");
        chatBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatBox1ActionPerformed(evt);
            }
        });
        chatBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chatBox1KeyPressed(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel3.setBackground(new java.awt.Color(0, 0, 0));
        panel3.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        chatBox2.setEditable(false);
        chatBox2.setColumns(20);
        chatBox2.setRows(5);
        jScrollPane3.setViewportView(chatBox2);

        pianoArea.setEditable(false);
        pianoArea.setColumns(20);
        pianoArea.setRows(5);
        pianoArea.setText("piano here");
        pianoArea.setToolTipText("");
        pianoArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pianoAreaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pianoAreaKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(pianoArea);

        panel62.setBackground(new java.awt.Color(0, 0, 0));
        panel62.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel62Layout = new javax.swing.GroupLayout(panel62);
        panel62.setLayout(panel62Layout);
        panel62Layout.setHorizontalGroup(
            panel62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel62Layout.setVerticalGroup(
            panel62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel63.setBackground(new java.awt.Color(0, 0, 0));
        panel63.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel63Layout = new javax.swing.GroupLayout(panel63);
        panel63.setLayout(panel63Layout);
        panel63Layout.setHorizontalGroup(
            panel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel63Layout.setVerticalGroup(
            panel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel64.setBackground(new java.awt.Color(0, 0, 0));
        panel64.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel64Layout = new javax.swing.GroupLayout(panel64);
        panel64.setLayout(panel64Layout);
        panel64Layout.setHorizontalGroup(
            panel64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel64Layout.setVerticalGroup(
            panel64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel65.setBackground(new java.awt.Color(0, 0, 0));
        panel65.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel65Layout = new javax.swing.GroupLayout(panel65);
        panel65.setLayout(panel65Layout);
        panel65Layout.setHorizontalGroup(
            panel65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel65Layout.setVerticalGroup(
            panel65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel66.setBackground(new java.awt.Color(0, 0, 0));
        panel66.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel66Layout = new javax.swing.GroupLayout(panel66);
        panel66.setLayout(panel66Layout);
        panel66Layout.setHorizontalGroup(
            panel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel66Layout.setVerticalGroup(
            panel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel67.setBackground(new java.awt.Color(0, 0, 0));
        panel67.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel67Layout = new javax.swing.GroupLayout(panel67);
        panel67.setLayout(panel67Layout);
        panel67Layout.setHorizontalGroup(
            panel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel67Layout.setVerticalGroup(
            panel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel68.setBackground(new java.awt.Color(0, 0, 0));
        panel68.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel68Layout = new javax.swing.GroupLayout(panel68);
        panel68.setLayout(panel68Layout);
        panel68Layout.setHorizontalGroup(
            panel68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel68Layout.setVerticalGroup(
            panel68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel69.setBackground(new java.awt.Color(0, 0, 0));
        panel69.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel69Layout = new javax.swing.GroupLayout(panel69);
        panel69.setLayout(panel69Layout);
        panel69Layout.setHorizontalGroup(
            panel69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel69Layout.setVerticalGroup(
            panel69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel70.setBackground(new java.awt.Color(0, 0, 0));
        panel70.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel70Layout = new javax.swing.GroupLayout(panel70);
        panel70.setLayout(panel70Layout);
        panel70Layout.setHorizontalGroup(
            panel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel70Layout.setVerticalGroup(
            panel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel71.setBackground(new java.awt.Color(0, 0, 0));
        panel71.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel71Layout = new javax.swing.GroupLayout(panel71);
        panel71.setLayout(panel71Layout);
        panel71Layout.setHorizontalGroup(
            panel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel71Layout.setVerticalGroup(
            panel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel72.setBackground(new java.awt.Color(0, 0, 0));
        panel72.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel72Layout = new javax.swing.GroupLayout(panel72);
        panel72.setLayout(panel72Layout);
        panel72Layout.setHorizontalGroup(
            panel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel72Layout.setVerticalGroup(
            panel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel73.setBackground(new java.awt.Color(0, 0, 0));
        panel73.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel73Layout = new javax.swing.GroupLayout(panel73);
        panel73.setLayout(panel73Layout);
        panel73Layout.setHorizontalGroup(
            panel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel73Layout.setVerticalGroup(
            panel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel74.setBackground(new java.awt.Color(0, 0, 0));
        panel74.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel74Layout = new javax.swing.GroupLayout(panel74);
        panel74.setLayout(panel74Layout);
        panel74Layout.setHorizontalGroup(
            panel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel74Layout.setVerticalGroup(
            panel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel75.setBackground(new java.awt.Color(0, 0, 0));
        panel75.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel75Layout = new javax.swing.GroupLayout(panel75);
        panel75.setLayout(panel75Layout);
        panel75Layout.setHorizontalGroup(
            panel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel75Layout.setVerticalGroup(
            panel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel76.setBackground(new java.awt.Color(0, 0, 0));
        panel76.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel76Layout = new javax.swing.GroupLayout(panel76);
        panel76.setLayout(panel76Layout);
        panel76Layout.setHorizontalGroup(
            panel76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel76Layout.setVerticalGroup(
            panel76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel77.setBackground(new java.awt.Color(0, 0, 0));
        panel77.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel77Layout = new javax.swing.GroupLayout(panel77);
        panel77.setLayout(panel77Layout);
        panel77Layout.setHorizontalGroup(
            panel77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel77Layout.setVerticalGroup(
            panel77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel78.setBackground(new java.awt.Color(0, 0, 0));
        panel78.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel78Layout = new javax.swing.GroupLayout(panel78);
        panel78.setLayout(panel78Layout);
        panel78Layout.setHorizontalGroup(
            panel78Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel78Layout.setVerticalGroup(
            panel78Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel79.setBackground(new java.awt.Color(0, 0, 0));
        panel79.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel79Layout = new javax.swing.GroupLayout(panel79);
        panel79.setLayout(panel79Layout);
        panel79Layout.setHorizontalGroup(
            panel79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel79Layout.setVerticalGroup(
            panel79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel80.setBackground(new java.awt.Color(0, 0, 0));
        panel80.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel80Layout = new javax.swing.GroupLayout(panel80);
        panel80.setLayout(panel80Layout);
        panel80Layout.setHorizontalGroup(
            panel80Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel80Layout.setVerticalGroup(
            panel80Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel81.setBackground(new java.awt.Color(0, 0, 0));
        panel81.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel81Layout = new javax.swing.GroupLayout(panel81);
        panel81.setLayout(panel81Layout);
        panel81Layout.setHorizontalGroup(
            panel81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel81Layout.setVerticalGroup(
            panel81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel82.setBackground(new java.awt.Color(0, 0, 0));
        panel82.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel82Layout = new javax.swing.GroupLayout(panel82);
        panel82.setLayout(panel82Layout);
        panel82Layout.setHorizontalGroup(
            panel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel82Layout.setVerticalGroup(
            panel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel83.setBackground(new java.awt.Color(0, 0, 0));
        panel83.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel83Layout = new javax.swing.GroupLayout(panel83);
        panel83.setLayout(panel83Layout);
        panel83Layout.setHorizontalGroup(
            panel83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel83Layout.setVerticalGroup(
            panel83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel84.setBackground(new java.awt.Color(0, 0, 0));
        panel84.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel84Layout = new javax.swing.GroupLayout(panel84);
        panel84.setLayout(panel84Layout);
        panel84Layout.setHorizontalGroup(
            panel84Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel84Layout.setVerticalGroup(
            panel84Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel85.setBackground(new java.awt.Color(0, 0, 0));
        panel85.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel85Layout = new javax.swing.GroupLayout(panel85);
        panel85.setLayout(panel85Layout);
        panel85Layout.setHorizontalGroup(
            panel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel85Layout.setVerticalGroup(
            panel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel86.setBackground(new java.awt.Color(0, 0, 0));
        panel86.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel86Layout = new javax.swing.GroupLayout(panel86);
        panel86.setLayout(panel86Layout);
        panel86Layout.setHorizontalGroup(
            panel86Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel86Layout.setVerticalGroup(
            panel86Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel87.setBackground(new java.awt.Color(0, 0, 0));
        panel87.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel87Layout = new javax.swing.GroupLayout(panel87);
        panel87.setLayout(panel87Layout);
        panel87Layout.setHorizontalGroup(
            panel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel87Layout.setVerticalGroup(
            panel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel88.setBackground(new java.awt.Color(0, 0, 0));
        panel88.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel88Layout = new javax.swing.GroupLayout(panel88);
        panel88.setLayout(panel88Layout);
        panel88Layout.setHorizontalGroup(
            panel88Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel88Layout.setVerticalGroup(
            panel88Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel89.setBackground(new java.awt.Color(0, 0, 0));
        panel89.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel89Layout = new javax.swing.GroupLayout(panel89);
        panel89.setLayout(panel89Layout);
        panel89Layout.setHorizontalGroup(
            panel89Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel89Layout.setVerticalGroup(
            panel89Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel90.setBackground(new java.awt.Color(0, 0, 0));
        panel90.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel90Layout = new javax.swing.GroupLayout(panel90);
        panel90.setLayout(panel90Layout);
        panel90Layout.setHorizontalGroup(
            panel90Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel90Layout.setVerticalGroup(
            panel90Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel91.setBackground(new java.awt.Color(0, 0, 0));
        panel91.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel91Layout = new javax.swing.GroupLayout(panel91);
        panel91.setLayout(panel91Layout);
        panel91Layout.setHorizontalGroup(
            panel91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel91Layout.setVerticalGroup(
            panel91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel92.setBackground(new java.awt.Color(0, 0, 0));
        panel92.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel92Layout = new javax.swing.GroupLayout(panel92);
        panel92.setLayout(panel92Layout);
        panel92Layout.setHorizontalGroup(
            panel92Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel92Layout.setVerticalGroup(
            panel92Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel93.setBackground(new java.awt.Color(0, 0, 0));
        panel93.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel93Layout = new javax.swing.GroupLayout(panel93);
        panel93.setLayout(panel93Layout);
        panel93Layout.setHorizontalGroup(
            panel93Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel93Layout.setVerticalGroup(
            panel93Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel94.setBackground(new java.awt.Color(0, 0, 0));
        panel94.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel94Layout = new javax.swing.GroupLayout(panel94);
        panel94.setLayout(panel94Layout);
        panel94Layout.setHorizontalGroup(
            panel94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel94Layout.setVerticalGroup(
            panel94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel95.setBackground(new java.awt.Color(0, 0, 0));
        panel95.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel95Layout = new javax.swing.GroupLayout(panel95);
        panel95.setLayout(panel95Layout);
        panel95Layout.setHorizontalGroup(
            panel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel95Layout.setVerticalGroup(
            panel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel96.setBackground(new java.awt.Color(0, 0, 0));
        panel96.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel96Layout = new javax.swing.GroupLayout(panel96);
        panel96.setLayout(panel96Layout);
        panel96Layout.setHorizontalGroup(
            panel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel96Layout.setVerticalGroup(
            panel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel97.setBackground(new java.awt.Color(0, 0, 0));
        panel97.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel97Layout = new javax.swing.GroupLayout(panel97);
        panel97.setLayout(panel97Layout);
        panel97Layout.setHorizontalGroup(
            panel97Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel97Layout.setVerticalGroup(
            panel97Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel98.setBackground(new java.awt.Color(0, 0, 0));
        panel98.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel98Layout = new javax.swing.GroupLayout(panel98);
        panel98.setLayout(panel98Layout);
        panel98Layout.setHorizontalGroup(
            panel98Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel98Layout.setVerticalGroup(
            panel98Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel99.setBackground(new java.awt.Color(0, 0, 0));
        panel99.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel99Layout = new javax.swing.GroupLayout(panel99);
        panel99.setLayout(panel99Layout);
        panel99Layout.setHorizontalGroup(
            panel99Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel99Layout.setVerticalGroup(
            panel99Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel100.setBackground(new java.awt.Color(0, 0, 0));
        panel100.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel100Layout = new javax.swing.GroupLayout(panel100);
        panel100.setLayout(panel100Layout);
        panel100Layout.setHorizontalGroup(
            panel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel100Layout.setVerticalGroup(
            panel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel101.setBackground(new java.awt.Color(0, 0, 0));
        panel101.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel101Layout = new javax.swing.GroupLayout(panel101);
        panel101.setLayout(panel101Layout);
        panel101Layout.setHorizontalGroup(
            panel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel101Layout.setVerticalGroup(
            panel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel102.setBackground(new java.awt.Color(0, 0, 0));
        panel102.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel102Layout = new javax.swing.GroupLayout(panel102);
        panel102.setLayout(panel102Layout);
        panel102Layout.setHorizontalGroup(
            panel102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel102Layout.setVerticalGroup(
            panel102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel103.setBackground(new java.awt.Color(0, 0, 0));
        panel103.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel103Layout = new javax.swing.GroupLayout(panel103);
        panel103.setLayout(panel103Layout);
        panel103Layout.setHorizontalGroup(
            panel103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel103Layout.setVerticalGroup(
            panel103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel104.setBackground(new java.awt.Color(0, 0, 0));
        panel104.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel104Layout = new javax.swing.GroupLayout(panel104);
        panel104.setLayout(panel104Layout);
        panel104Layout.setHorizontalGroup(
            panel104Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel104Layout.setVerticalGroup(
            panel104Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel105.setBackground(new java.awt.Color(0, 0, 0));
        panel105.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel105Layout = new javax.swing.GroupLayout(panel105);
        panel105.setLayout(panel105Layout);
        panel105Layout.setHorizontalGroup(
            panel105Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel105Layout.setVerticalGroup(
            panel105Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel106.setBackground(new java.awt.Color(0, 0, 0));
        panel106.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel106Layout = new javax.swing.GroupLayout(panel106);
        panel106.setLayout(panel106Layout);
        panel106Layout.setHorizontalGroup(
            panel106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel106Layout.setVerticalGroup(
            panel106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel107.setBackground(new java.awt.Color(0, 0, 0));
        panel107.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel107Layout = new javax.swing.GroupLayout(panel107);
        panel107.setLayout(panel107Layout);
        panel107Layout.setHorizontalGroup(
            panel107Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel107Layout.setVerticalGroup(
            panel107Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel108.setBackground(new java.awt.Color(0, 0, 0));
        panel108.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel108Layout = new javax.swing.GroupLayout(panel108);
        panel108.setLayout(panel108Layout);
        panel108Layout.setHorizontalGroup(
            panel108Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel108Layout.setVerticalGroup(
            panel108Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel109.setBackground(new java.awt.Color(0, 0, 0));
        panel109.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel109Layout = new javax.swing.GroupLayout(panel109);
        panel109.setLayout(panel109Layout);
        panel109Layout.setHorizontalGroup(
            panel109Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel109Layout.setVerticalGroup(
            panel109Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel110.setBackground(new java.awt.Color(0, 0, 0));
        panel110.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel110Layout = new javax.swing.GroupLayout(panel110);
        panel110.setLayout(panel110Layout);
        panel110Layout.setHorizontalGroup(
            panel110Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel110Layout.setVerticalGroup(
            panel110Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel111.setBackground(new java.awt.Color(0, 0, 0));
        panel111.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel111Layout = new javax.swing.GroupLayout(panel111);
        panel111.setLayout(panel111Layout);
        panel111Layout.setHorizontalGroup(
            panel111Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel111Layout.setVerticalGroup(
            panel111Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel112.setBackground(new java.awt.Color(0, 0, 0));
        panel112.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel112Layout = new javax.swing.GroupLayout(panel112);
        panel112.setLayout(panel112Layout);
        panel112Layout.setHorizontalGroup(
            panel112Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel112Layout.setVerticalGroup(
            panel112Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel113.setBackground(new java.awt.Color(0, 0, 0));
        panel113.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel113Layout = new javax.swing.GroupLayout(panel113);
        panel113.setLayout(panel113Layout);
        panel113Layout.setHorizontalGroup(
            panel113Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel113Layout.setVerticalGroup(
            panel113Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel114.setBackground(new java.awt.Color(0, 0, 0));
        panel114.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel114Layout = new javax.swing.GroupLayout(panel114);
        panel114.setLayout(panel114Layout);
        panel114Layout.setHorizontalGroup(
            panel114Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel114Layout.setVerticalGroup(
            panel114Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel115.setBackground(new java.awt.Color(0, 0, 0));
        panel115.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel115Layout = new javax.swing.GroupLayout(panel115);
        panel115.setLayout(panel115Layout);
        panel115Layout.setHorizontalGroup(
            panel115Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel115Layout.setVerticalGroup(
            panel115Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel116.setBackground(new java.awt.Color(0, 0, 0));
        panel116.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel116Layout = new javax.swing.GroupLayout(panel116);
        panel116.setLayout(panel116Layout);
        panel116Layout.setHorizontalGroup(
            panel116Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel116Layout.setVerticalGroup(
            panel116Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel117.setBackground(new java.awt.Color(0, 0, 0));
        panel117.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel117Layout = new javax.swing.GroupLayout(panel117);
        panel117.setLayout(panel117Layout);
        panel117Layout.setHorizontalGroup(
            panel117Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel117Layout.setVerticalGroup(
            panel117Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel118.setBackground(new java.awt.Color(0, 0, 0));
        panel118.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel118Layout = new javax.swing.GroupLayout(panel118);
        panel118.setLayout(panel118Layout);
        panel118Layout.setHorizontalGroup(
            panel118Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel118Layout.setVerticalGroup(
            panel118Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel119.setBackground(new java.awt.Color(0, 0, 0));
        panel119.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel119Layout = new javax.swing.GroupLayout(panel119);
        panel119.setLayout(panel119Layout);
        panel119Layout.setHorizontalGroup(
            panel119Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel119Layout.setVerticalGroup(
            panel119Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel120.setBackground(new java.awt.Color(0, 0, 0));
        panel120.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel120Layout = new javax.swing.GroupLayout(panel120);
        panel120.setLayout(panel120Layout);
        panel120Layout.setHorizontalGroup(
            panel120Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel120Layout.setVerticalGroup(
            panel120Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel121.setBackground(new java.awt.Color(0, 0, 0));
        panel121.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel121Layout = new javax.swing.GroupLayout(panel121);
        panel121.setLayout(panel121Layout);
        panel121Layout.setHorizontalGroup(
            panel121Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel121Layout.setVerticalGroup(
            panel121Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel122.setBackground(new java.awt.Color(0, 0, 0));
        panel122.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel122Layout = new javax.swing.GroupLayout(panel122);
        panel122.setLayout(panel122Layout);
        panel122Layout.setHorizontalGroup(
            panel122Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel122Layout.setVerticalGroup(
            panel122Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel123.setBackground(new java.awt.Color(0, 0, 0));
        panel123.setPreferredSize(new java.awt.Dimension(10, 200));

        javax.swing.GroupLayout panel123Layout = new javax.swing.GroupLayout(panel123);
        panel123.setLayout(panel123Layout);
        panel123Layout.setHorizontalGroup(
            panel123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel123Layout.setVerticalGroup(
            panel123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(chatBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel69, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel89, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel91, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel90, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel79, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel119, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel118, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel121, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel120, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel123, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel122, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel93, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel92, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel97, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel96, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel99, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel98, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel95, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel94, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel113, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel112, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel115, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel114, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel117, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel116, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel107, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel109, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel108, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel111, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel110, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panel104, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chatBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel69, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel89, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel90, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel91, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel79, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel118, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel119, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel120, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel121, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel122, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel123, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel92, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel93, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel96, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel97, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel98, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel99, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel94, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel95, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel112, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel113, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel114, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel115, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel116, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel117, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel107, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel108, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel109, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel110, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel111, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel104, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chatBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chatBox1ActionPerformed

    private void chatBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chatBox1KeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        switch(key){
            case 10:
                try{
                    PianoClient.out.writeUTF("." + chatBox1.getText());
                }catch(IOException e){
                    
                }
                chatBox1.setText("");
                break;
            default:
        }
    }//GEN-LAST:event_chatBox1KeyPressed

    private void pianoAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pianoAreaKeyPressed
        // TODO add your handling code here:
        int keyInt = evt.getKeyCode();
        char keyChar = evt.getKeyChar();
        if (keyInt == 16){
            shiftDown = true;
        }
        if(shiftDown){
            try{
                PianoClient.out.writeUTF(Character.toString(keyChar));
            }catch(IOException e){
                
            }
        }else{
            try{
                PianoClient.out.writeUTF(Character.toString(keyChar).toLowerCase());
            }catch(IOException e){
                
            }
        }
    }//GEN-LAST:event_pianoAreaKeyPressed

    private void pianoAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pianoAreaKeyReleased
        // TODO add your handling code here:
        int keyInt = evt.getKeyCode();
        if (keyInt == 16){
            shiftDown = false;
        }
    }//GEN-LAST:event_pianoAreaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PianoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PianoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PianoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PianoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PianoGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField chatBox1;
    public static javax.swing.JTextArea chatBox2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static java.awt.Panel panel1;
    public static java.awt.Panel panel100;
    public static java.awt.Panel panel101;
    public static java.awt.Panel panel102;
    public static java.awt.Panel panel103;
    public static java.awt.Panel panel104;
    public static java.awt.Panel panel105;
    public static java.awt.Panel panel106;
    public static java.awt.Panel panel107;
    public static java.awt.Panel panel108;
    public static java.awt.Panel panel109;
    public static java.awt.Panel panel110;
    public static java.awt.Panel panel111;
    public static java.awt.Panel panel112;
    public static java.awt.Panel panel113;
    public static java.awt.Panel panel114;
    public static java.awt.Panel panel115;
    public static java.awt.Panel panel116;
    public static java.awt.Panel panel117;
    public static java.awt.Panel panel118;
    public static java.awt.Panel panel119;
    public static java.awt.Panel panel120;
    public static java.awt.Panel panel121;
    public static java.awt.Panel panel122;
    public static java.awt.Panel panel123;
    public static java.awt.Panel panel3;
    private java.awt.Panel panel4;
    public static java.awt.Panel panel62;
    public static java.awt.Panel panel63;
    public static java.awt.Panel panel64;
    public static java.awt.Panel panel65;
    public static java.awt.Panel panel66;
    public static java.awt.Panel panel67;
    public static java.awt.Panel panel68;
    public static java.awt.Panel panel69;
    public static java.awt.Panel panel70;
    public static java.awt.Panel panel71;
    public static java.awt.Panel panel72;
    public static java.awt.Panel panel73;
    public static java.awt.Panel panel74;
    public static java.awt.Panel panel75;
    public static java.awt.Panel panel76;
    public static java.awt.Panel panel77;
    public static java.awt.Panel panel78;
    public static java.awt.Panel panel79;
    public static java.awt.Panel panel80;
    public static java.awt.Panel panel81;
    public static java.awt.Panel panel82;
    public static java.awt.Panel panel83;
    public static java.awt.Panel panel84;
    public static java.awt.Panel panel85;
    public static java.awt.Panel panel86;
    public static java.awt.Panel panel87;
    public static java.awt.Panel panel88;
    public static java.awt.Panel panel89;
    public static java.awt.Panel panel90;
    public static java.awt.Panel panel91;
    public static java.awt.Panel panel92;
    public static java.awt.Panel panel93;
    public static java.awt.Panel panel94;
    public static java.awt.Panel panel95;
    public static java.awt.Panel panel96;
    public static java.awt.Panel panel97;
    public static java.awt.Panel panel98;
    public static java.awt.Panel panel99;
    private javax.swing.JTextArea pianoArea;
    // End of variables declaration//GEN-END:variables
}

